### ISSUE TITLE
Kein Abspielen nach langer idle Zeit mehr möglich

### ISSUE THREAD

**Issue by passuff** [splitti/MuPiBox#10]
Da der idle shutdown aktuell nicht wirklich funktioniert, bleibt die Box auch gerne mal 10h Stunden oder auch länger an ohne etwas abzuspielen. Wenn man dann etwas abspielen möchte, geht das nicht:
1. Fall: Es wird eine Google Seite mit irgendeinem Fehler angezeigt.
2. Fall: Die Oberfläche sieht normal aus, Titel können aber generell nicht abgespielt werden. Ähnlich als wäre keine Wifi/Internetverbindung vorhanden. 
 Ein Neustart behebt das Problem natürlich.

**Comment by splitti** [comment]
Ist dies nach dem Update ebenso der Fall?

**Comment by nero0345** [comment]
Das Problem sollte schon seit längeren gelöst sein.
