### ISSUE TITLE
Start up time verlängert sich kontinuierlich

### ISSUE THREAD

**Issue by passuff** [splitti/MuPiBox#11]
Eine frisch aufgesetzte Box mit importierten Einstellungen startet  bei mir in ca 16 Sekunden. Nach nun 3 Wochen sind daraus 46 Sekunden geworden, ohne dass eine Änderung vorgenommen wurde.

**Comment by splitti** [comment]
Wie schaltest Du die Box ein oder aus?

**Comment by passuff** [comment]
Mit dem on/off shim.

splitti ***@***.***> schrieb am Mi., 5. Okt. 2022, 20:23:

**Comment by splitti** [comment]
Besteht das Problem noch immer?

**Comment by passuff** [comment]
Nein, ist seit 2.04 nicht mehr aufgetreten.

splitti ***@***.***> schrieb am Mi., 28. Dez. 2022, 03:57:

**Comment by Hunv** [comment]
Moin,
ich habe das Problem auch. Und zwar mit Version 3.0.1.
Der Boot mit eine Raspi 4 1GB benötigt
- bis zum Abspielen des Startsounds ca. 21 Sekunden
- bis ich die Seite mit den Hörbüchern und deren Artist icons (alles Spotify) sehe: ca. 34 Sekunden

Das war früher definitiv mal schneller und mein Gefühl über die letzten Monate ist, dass es immer länger wird.
Die MuPiBox ist seit Weihnachten 2022 im Betrieb.

**Comment by nero0345** [comment]
Das Problem sollte schon seit längeren gelöst sein.
