### ISSUE TITLE
Cannot add or play Spotify playlist URL

### ISSUE THREAD

**Issue by AndroidFactoryDE** [splitti/MuPiBox#110]
I have updated to latest Mupibox version 4.2.1 today (from version 4.1.4).
After the update I cannot play or add Spotify playlist URLs anymore.

Spotify playlist URLs had worked with version 4.1.4.
Spotify album URLs are still playing, so the box is connected to Spotify.

 
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/4489053c-07d8-44bb-801e-e7a429c713cd">

**Comment by b-nobis** [comment]
The problem is not the version, but a change in the WebApi of Spotify yesterday: https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

Point 8: Algorithmic and Spotify-owned editorial playlists
They are no longer allowed to be accessed by the WebApi.
