### ISSUE TITLE
Featurerequest: Sleeptimer

### ISSUE THREAD

**Issue by tom3kcgn** [splitti/MuPiBox#16]
Ich möchte im Player einen Sleeptimer setzen können.
Optionen:
* 15 Minuten
* 30 Minuten
* 60 Minuten
* Am Ende des Tracks
* Am Ende des Albums / Hörspiel

**Comment by hyperbit00** [comment]
Ich kann diesen requests nur unterstützen. Hatte bisher Probleme mit dem IdleTimer. Dieser hat (zumindest bis Dev 1.0.10) nicht immer zuverlässig die Box abgeschaltet.

Ein Sleeptimer kann daher evtl helfen.

Wurde die Zeit noch un einen eigenen Wert erweitern, damit eine Freie Laufzeit bestimmt werden kann .

**Comment by splitti** [comment]
Der Idletimer ist gefixt. Ist denn ein genereller Timer, der nicht abhängig davon ist, ob gerade etwas gespielt wird oder nicht, weiterhin erwünscht?

**Comment by tom3kcgn** [comment]
Trotz des idle Timer fände ich die Option Klasse.
Hat aber keine so hohe Prio.

**Comment by splitti** [comment]
Wie stellt Ihr Euch den Timer denn vor? Aktivierung im Admin-Interface? Oder eine generelle Einstellung?

**Comment by tom3kcgn** [comment]
> Wie stellt Ihr Euch den Timer denn vor? Aktivierung im Admin-Interface? Oder eine generelle Einstellung?

**Comment by tom3kcgn** [comment]
Ich denke im Adminbereich reicht das aus, da die Kids das selbständig nicht können (jedenfalls die kleineren nicht) und der Knopf sonst nur zur Verwirrung führt.

**Comment by hyperbit00** [comment]
Tatsächlich dort wo auch der Idletimer eingestellt wird =) wird.

#Offtopic ein + & - bei der Lautstärkeeinstellung (in den Einstellungen) wäre auch fein. Auf einem Smartphone ist dieser Sliderbalken nur schwer zu bedienen (Entschuldigung fürs #offtopic)

**Comment by splitti** [comment]
Wird im kommenden Release berücksichtigt!
