### ISSUE TITLE
Feature request: Add possibility to use RFID chips to select playlists, etc. (like with Phoniebox)

### ISSUE THREAD

**Issue by baguenth** [splitti/MuPiBox#18]
To combine the best features of MuPi- and Phonie-Box it would be great, if playlists, radio channels etc. could also be selected via RFID chip. This would enable the MuPi-Box also for smaller childs, which are not able to use a touch screen, yet :)

**Comment by nero0345** [comment]
This function is currently not planned and cannot be implemented easily with the possibilities of the box.
