### ISSUE TITLE
Issue with Index of Sources

### ISSUE THREAD

**Issue by rg-one-two** [splitti/MuPiBox#21]
Hi there, first of all, I wanted to say that I love this project, thanks for all your work! 
I have an issue: I added various music sources to the mupibox and everything was fine. Then I added one more, they appeared in the "magic screen" (click 10 times), but not in the music / radio menus. Could it be due to the missing indexes, see screenshot?
![image](https://user-images.githubusercontent.com/45169956/225467324-92aeaf59-0ae1-48bb-80a7-36099ef69ef6.png)
Cheers, 
Rob

**Comment by nero0345** [comment]
That sound like a litte bug in the index, this problem shut be solved. Update to new Version and add new.
