### ISSUE TITLE
Now way to add local audiobooks/music sources

### ISSUE THREAD

**Issue by mprotogerakis** [splitti/MuPiBox#22]
in 3.0.1 adding files via Samba to the respective folders works but the "add media" menu only shows Spotify and radio streams options for adding.

**Comment by splitti** [comment]
Hey,
after uploading the media, you have to go into the admin-frontend. Click on admin -> Music database -> Update mediadata:
![image](https://user-images.githubusercontent.com/45425109/232320710-1b8df118-b7b1-417c-8e0a-74ed1220073a.png)
