### ISSUE TITLE
Changing display brightness is shown in percent but handled in byte

### ISSUE THREAD

**Issue by Hunv** [splitti/MuPiBox#26]
Hi,

if you move the slider of the display brightness in the display settings i.e. to 20% and click on submit, it shows in the "saved"-Message the value "brightness: 51" (which is 20% of 255). The slider also slides to 51% instead of 20% after submit was clicked.
I think there is a cast missing between 255 based and 100 based percentages.

**Comment by splitti** [comment]
Hi,

you are right. The problem will be fixed in the common releases 3.2.6 above.

Greetings
