### ISSUE TITLE
Incorrect / old TTS files after changing TTS Language

### ISSUE THREAD

**Issue by rgrollfitz** [splitti/MuPiBox#28]
Initially the TTS language is set to English. If, before changing this default, one of the titles is read out and then the language is changed, the old TTS audio file will be used, since its stored locally _(/home/dietpi/MuPiBox/tts_files/)_

Presumably the TTS files are stored locally to avoid having to access the TTS API again (which most likely only allows limited access) when playing repeatedly.

Maybe it would be possible to attach an identifier to the TTS file, which is updated as soon as this language identifier differs from the currently set TTS language.

**Comment by splitti** [comment]
Fixed in new versions

**Comment by MarkusLange** [comment]
Looks like it's back in 4.2.1
