### ISSUE TITLE
keine WLAN Verbindung möglich

### ISSUE THREAD

**Issue by hollywoot** [splitti/MuPiBox#34]
Hi,
habe eben die neueste 64bit Variante geladen und auf die SD Karte des RPi4 geschrieben.

Die `add_wifi.json` funktioniert nicht.
Sie sieht folgendermaßen aus:
```
{
	"ssid": "Your Wifi-Name",
	"password": "Your Wifi-Password"
``` 
Es fehlt die abschließende Klammer? 
Es ist aber auch egal ob mit oder ohne. Die Box verbindet sich nicht.
```
{
	"ssid": "Meine-SSID",
	"password": "p@ssw0rt"
``` 
Auch wenn ich das WLAN direkt in der Box über die Oberfläche eintrage hat es keine Wirkung.

*Workaround:*
Verbindung über eth-Schnittstelle herstellen und WLAn-Verbindung mittels `dietpi-config` herstellen. Das funktioniert.

**Comment by nero0345** [comment]
Im neuen Update umgesetzt.
