### ISSUE TITLE
Update within the webinterface does not change the version of the installation

### ISSUE THREAD

**Issue by MarkusLange** [splitti/MuPiBox#36]
If I update the mupibox from the admininterface, the version number doesn't change for the box it still believe its the same version I original installed with the SD Card. In my case the Box is still 3.1.9 but I allready updated to version 3.2.4 with the admininterface

**Comment by splitti** [comment]
Hi Markus,

the problem should be solved on the next update. Problems were fixed.

Greetings

**Comment by MarkusLange** [comment]
Still thinks it's version 3.1.9

**Comment by splitti** [comment]
> Still thinks it's version 3.1.9

Please do a manual update in shell. More information here: https://mupibox.de/wenn-das-update-nicht-funktioniert/

**Comment by MarkusLange** [comment]
new it works, thanks
