### ISSUE TITLE
duplicate entries in resume list

### ISSUE THREAD

**Issue by AndroidFactoryDE** [splitti/MuPiBox#47]
System:
- RPI4, 4GB, Boot from Samsung USB Stick 128GB
- MuPiHAT

Software:
- MuPiBox Image 4.0.4

Current behavior:
- the resume list contains duplicate entries from the same album

Expected behavior:
- the resume list contains only one entry for the same album

Appendix:
- [resume.json](https://github.com/splitti/MuPiBox/files/14803296/resume.json) (source: /home/dietpie/.mupibox/Sonos-Kids-Controler-master/server/config/resume.json)

**Comment by nero0345** [comment]
done
