### ISSUE TITLE
Change sound output to headphone jack

### ISSUE THREAD

**Issue by oswaldo-be** [splitti/MuPiBox#6]
Hej there,

thank you very much for this project. I only have one phoniebox with the hifiberry.
The other one works with the headphone jack.
Can you give a short explanation please how I can change it?
I fiddled around with phoniebox for one year and have little experience in the config how this worked...

Thank you very much

**Comment by nero0345** [comment]
Hello,

the question is whether you want to use only the headphone jack or the Hifiberry on the MuPiBox, or both. I have made after much testing the experience that both is really heavy and also the quality is not so good. But you can use both with the MuPiBox and depending on what you just want to have in the web interface easily select. Then the output is only output via dise output. The automatic change does not work with it. But what works are Bluetooth headphones and so the automatic switch works.
I hope I could help you.
If you have further questions, just come to our Discord and we can help you even more.

https://discord.gg/4EjCgpCbbe

nero0345

**Comment by splitti** [comment]
In version 1.0.8 the jack is an option in the configuration.
