### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by varac** [splitti/MuPiBox#7]
Hej, thanks for this project, it looks really nice!
Before I try it: How would I upgrade to newer versions ? Please add upgrade instructions (coming from http://phoniebox.de/ where upgrades weren't the easiest task).

**Comment by nero0345** [comment]
Hallo,
If you come from phoniebox, you need a touchdisplay and a new installation on the sd-card.
In the webinterface you have a option to update the newest version of mupibox only with one click.
