### ISSUE TITLE
https://  Radio Streams need a long time to start (40 - 60 seconds)

### ISSUE THREAD

**Issue by calibrationcube** [splitti/MuPiBox#79]
Radiostreams with an https:// Link need a long time, till the playback starts
In some cases almost 60s.

I testetd this with the actual DEV 2024-10-30:

DLF HTTP
Stream: http://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3?aggregator=web (starttime 2s)

DLF HTTPS
Stream: https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3?aggregator=web (starttime 40s)

important note:
Strem URLS can not be placed in the same Label. 
In my case i tried to label both Links as RADIO. But in the JSON he chnged both Links to HTTP or HTTPS. depends which on was saved first.

**Comment by nero0345** [comment]
done, new saved url in rss or radio is change from https to http
