### ISSUE TITLE
Startlautstärke variiert

### ISSUE THREAD

**Issue by passuff** [splitti/MuPiBox#8]
Ich habe 20 % als Startlautstärke eingestellt. Nach einem Start steht die Lautstärke auch manchmal auf 20%, dann aber wieder auf 25%, 30% oder auch 35%.
Ich vermute das ist nicht gewollt..

**Comment by splitti** [comment]
Hast Du dieses Problem nach dem Release noch immer? Ich kann das nicht nachstellen

**Comment by passuff** [comment]
Nein, mit dem neuen Release ist es nicht mehr aufgetaucht. Kann geschlossen
werden.

splitti ***@***.***> schrieb am Mi., 5. Okt. 2022, 20:20:
