### ISSUE TITLE
Idle Shutdown funktioniert nicht

### ISSUE THREAD

**Issue by passuff** [splitti/MuPiBox#9]
Anfänglich hat der idle shutdown für mich funktioniert. Nach einer Änderung von 5 min auf 10 min funktioniert es leider nicht mehr. Auch eine Änderung zurück auf 5 Minuten bringt keine Besserung.

**Comment by hyperbit00** [comment]
Ich hatte meinen idle Timer in der Dev 1.0.10 auf 6 Minuten gesetzt und habe dieses Verhalten bisher auch zwei Mal beobachten können.

Der idletime braucht evtl etwas Developer Aufmerksamkeit.

**Comment by splitti** [comment]
Fixed
